# Generated by Django 3.0.1 on 2020-03-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Amount',
            new_name='amount',
        ),
    ]
