# Generated by Django 3.0.1 on 2020-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensify', '0002_auto_20200310_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
